# Generated by Django 4.1.5 on 2023-02-12 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MotorPlus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('vehicle_class', models.CharField(max_length=30)),
                ('fuel_type', models.CharField(max_length=30)),
                ('transmission', models.CharField(max_length=30)),
                ('city_mpg', models.FloatField()),
                ('highway_mpg', models.FloatField()),
                ('displacement', models.FloatField()),
                ('cylinders', models.FloatField()),
                ('calculated_mpg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='APIMotorcycle',
            new_name='APIVehicle',
        ),
        migrations.DeleteModel(
            name='Motorcycle',
        ),
        migrations.AlterField(
            model_name='profile',
            name='motorcycles',
            field=models.ManyToManyField(to='MotorPlus.vehicle'),
        ),
    ]
