# Generated by Django 4.1.4 on 2023-02-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MotorPlus", "0002_vehicle_rename_apimotorcycle_apivehicle_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle",
            old_name="calculated_mpg",
            new_name="combination_mpg_api",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="combination_mpg_predicted",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
