# Generated by Django 4.1.7 on 2023-04-11 23:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="API_KEY",
        ),
    ]
