# Generated by Django 4.1.7 on 2023-04-12 01:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_user_secret_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="secret_key",
        ),
    ]
