# Generated by Django 4.1.7 on 2023-04-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_remove_user_secret_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="API_KEY",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
