# Generated by Django 4.1.7 on 2023-04-05 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=30)),
                ("model", models.CharField(max_length=30)),
                ("year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=30)),
                ("model", models.CharField(max_length=30)),
                ("year", models.IntegerField()),
                ("vehicle_class", models.CharField(max_length=30)),
                ("fuel_type", models.CharField(max_length=30)),
                ("transmission", models.CharField(max_length=30)),
                ("city_mpg", models.FloatField()),
                ("highway_mpg", models.FloatField()),
                ("displacement", models.FloatField()),
                ("cylinders", models.FloatField()),
                (
                    "combination_mpg_api",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "combination_mpg_predicted",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
