# Generated by Django 4.1.7 on 2023-04-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="city_mpg",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="combination_mpg_api",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="combination_mpg_predicted",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="fuel_type",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="highway_mpg",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="vehicle_class",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="acceleration",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="horsepower",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="mpg_api",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="mpg_predicted",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="origin",
            field=models.CharField(
                choices=[("USA", "USA"), ("Europe", "Europe"), ("Japan", "Japan")],
                default=0,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="weight",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="transmission",
            field=models.CharField(max_length=1),
        ),
    ]
