# Generated by Django 4.1.7 on 2023-04-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0002_remove_vehicle_city_mpg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="is_custom",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="name",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
    ]
